# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPdb < Formula
  desc ""
  homepage ""
  version "0.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.1/kubectl-pdb_Darwin_arm64.tar.gz"
      sha256 "4c1abe50510adda113278f5b88597b887647a08b3f456c826a32d0b85783bcb3"

      def install
        bin.install "kubectl-pdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.1/kubectl-pdb_Darwin_x86_64.tar.gz"
      sha256 "0bc971d9f93915032893253c1831346cce76f1b6a547602d0a85e24741b97436"

      def install
        bin.install "kubectl-pdb"
      end
    end
  end
end
