# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlEvict < Formula
  desc ""
  homepage "https://github.com/dhenkel92/kubectl-pdb"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.5/kubectl-evict_Darwin_x86_64.tar.gz"
      sha256 "b494c05371a105104d2ca96e924c81c6acec56563c3b33b79f6595ac67df1a74"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.5/kubectl-evict_Darwin_arm64.tar.gz"
      sha256 "f2685dfae9f6951a372a5f773e2607e60a68bc29ea734ee44b5ac3df27f020e1"

      def install
        bin.install "kubectl-evict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.5/kubectl-evict_Linux_armv6.tar.gz"
      sha256 "dbcdd560b5d42a3ef372fe1e74e49fe97d92baa86847b6576646bd2c3a0665d5"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.5/kubectl-evict_Linux_x86_64.tar.gz"
      sha256 "33087bb3284eedd83101fb0eb3867da91ea878c203c7d1f9629748a48742902c"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.5/kubectl-evict_Linux_arm64.tar.gz"
      sha256 "8d6745f68c748d93dcbe78a9c7d5ca92e79940c3fe253f4805737db3a50006be"

      def install
        bin.install "kubectl-evict"
      end
    end
  end
end
