# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDebugPdb < Formula
  desc ""
  homepage "https://github.com/dhenkel92/kubectl-debug-pdb"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.1/kubectl-debug-pdb_Darwin_arm64.tar.gz"
      sha256 "dc295bd723b56c331a5392a5ff87e1a62f7e0b84a8cea6d0c137a2030b75d81a"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.1/kubectl-debug-pdb_Darwin_x86_64.tar.gz"
      sha256 "47b8d939012c55ad94048e1b3b01723ff9590ad614c3316cd694d1c2e66cb32c"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.1/kubectl-debug-pdb_Linux_x86_64.tar.gz"
      sha256 "72b5ba621e3a9250b9408325cada87f7bc6828e752c218fefcd0dd8d15f969a0"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.1/kubectl-debug-pdb_Linux_armv6.tar.gz"
      sha256 "80849ab8e2c6c64169e7d92e0ced16f8a561c816ad9abe7920a2016704b10096"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.1/kubectl-debug-pdb_Linux_arm64.tar.gz"
      sha256 "1438007677dd8896bbdf9f21af9a1ff1ded5417641f0f1c828317e33ef9af065"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
  end
end
