# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDebugPdb < Formula
  desc ""
  homepage "https://github.com/dhenkel92/kubectl-debug-pdb"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.0/kubectl-pdb_Darwin_x86_64.tar.gz"
      sha256 "4d505a994d18c35be771c33bd1effe13bdc2766b435cfb24331fab6b7dc98f90"

      def install
        bin.install "kubectl-debug-pdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.0/kubectl-pdb_Darwin_arm64.tar.gz"
      sha256 "7499dde495f204c7858e803133f81a64cabbe39d30e62b476443e2c5bd3c8a53"

      def install
        bin.install "kubectl-debug-pdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.0/kubectl-pdb_Linux_armv6.tar.gz"
      sha256 "d229bfce7bba1d10f6464f4c50c2882bb783f96cddda3194033bbb9e659b9788"

      def install
        bin.install "kubectl-debug-pdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.0/kubectl-pdb_Linux_arm64.tar.gz"
      sha256 "6eacf0bcfa7f20cec3e00289ea452e2ef3997753eed3acaac77b035a019ab65a"

      def install
        bin.install "kubectl-debug-pdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.1.0/kubectl-pdb_Linux_x86_64.tar.gz"
      sha256 "fa5ef13f96d6ed543affb22e158a8b7c9410e0d7dbcf4402d46f5664ad313b2f"

      def install
        bin.install "kubectl-debug-pdb"
      end
    end
  end
end
