# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDebugPdb < Formula
  desc ""
  homepage "https://github.com/dhenkel92/kubectl-debug-pdb"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/v0.1.2/kubectl-debug-pdb_Darwin_x86_64.tar.gz"
      sha256 "1daed7deb983c3c0d5c639985ff799807fad97fdd6156320ecd4a4d3195e7936"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/v0.1.2/kubectl-debug-pdb_Darwin_arm64.tar.gz"
      sha256 "0e8d67624cbdd906e4854d9ec90317afbffe1d539bb76a37a502b0a87032dbb5"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/v0.1.2/kubectl-debug-pdb_Linux_armv6.tar.gz"
      sha256 "43205c8bc119712ea74f43bebf58662f6f0e2a01fb7ec2ba74acb179a6a5520c"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/v0.1.2/kubectl-debug-pdb_Linux_arm64.tar.gz"
      sha256 "9ed7c3ae7199379bb92adc7210321d537c7b527d8ec24db5d484be326b9b3b78"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/v0.1.2/kubectl-debug-pdb_Linux_x86_64.tar.gz"
      sha256 "074730db6f031db36d25ee57ae01827b60cd6c724797126883f1a92bf93de395"

      def install
        bin.install "kubectl-debug_pdb"
      end
    end
  end
end
