# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlEvict < Formula
  desc ""
  homepage "https://github.com/dhenkel92/kubectl-pdb"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.6/kubectl-evict_Darwin_arm64.tar.gz"
      sha256 "ab95922a15c068a8e9923efac6111cb9613d67a2ac9764caf91d22533db46128"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.6/kubectl-evict_Darwin_x86_64.tar.gz"
      sha256 "778a8ccf4bc887cb75c67dab9bfc7231d743b65946623e4745919252b02af9c2"

      def install
        bin.install "kubectl-evict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.6/kubectl-evict_Linux_armv6.tar.gz"
      sha256 "759577f4bf3e8eb9c05505164582ff2069db5d051582fbc29c98fc51880c500e"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.6/kubectl-evict_Linux_x86_64.tar.gz"
      sha256 "92a0493cbdda83a5fd97e7b5f8a3f818c9ccc360d0ab3f733fa674b69a7bed73"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/kubectl-pdb/releases/download/v0.0.6/kubectl-evict_Linux_arm64.tar.gz"
      sha256 "4c2d2f958c185d3bb017a2546213d58d1d64f696f3bd48931e3f5b61ff1adf1a"

      def install
        bin.install "kubectl-evict"
      end
    end
  end
end
