# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDsh < Formula
  desc "Kubernetes DSH Plugin"
  homepage "https://github.com/dhenkel92/pod-helper"
  version "0.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dhenkel92/pod-helper/releases/download/v0.1.9/kubectl-dsh_0.1.9_Darwin_x86_64.tar.gz"
    sha256 "ba6a46609ec890a66a3e85ad42a08fe3563e3488ca1f2ca1884f684ea0e72271"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/pod-helper/releases/download/v0.1.9/kubectl-dsh_0.1.9_Linux_x86_64.tar.gz"
      sha256 "5765684ba8795a0a18d0b47cf579cb6443c5eb488aaa9df361462e04c69a45c8"
    end
  end

  def install
    bin.install "pod-helper"
    bin.install "kubectl-dsh"
  end

  test do
    system "#{bin}/kubectl-dsh -h"
  end
end
