# This file was generated by GoReleaser. DO NOT EDIT.
class PodHelper < Formula
  desc "Kubernetes Pod Helper Util"
  homepage "https://github.com/dhenkel92/pod-helper"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dhenkel92/pod-helper/releases/download/v0.1.1/pod-helper_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "d229d5f6753e133078c26bb4db8642ca640c664f305d6f0e916a5e20ca10c02e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/pod-helper/releases/download/v0.1.1/pod-helper_0.1.1_Linux_x86_64.tar.gz"
      sha256 "954beb0bf3f29e14c3663739a61fa5c903b4e7f15aff11c2f38119becd00684a"
    end
  end

  def install
    bin.install "pod-helper"
  end

  test do
    system "#{bin}/pod-helper -h"
  end
end
