# This file was generated by GoReleaser. DO NOT EDIT.
class PodHelper < Formula
  desc "Kubernetes Pod Helper Util"
  homepage "https://github.com/dhenkel92/pod-helper"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dhenkel92/pod-helper/releases/download/v0.1.4/pod-helper_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "0ed5300bd3dba3902ddbaf20c7eb1495b7ed5c918ef1512d196ba89c18e3d729"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/pod-helper/releases/download/v0.1.4/pod-helper_0.1.4_Linux_x86_64.tar.gz"
      sha256 "25e4e8cb4bf5c85622cb79c427548a7886682e62eb26e22ae18da2e14a02c757"
    end
  end

  def install
    bin.install "pod-helper"
  end

  test do
    system "#{bin}/pod-helper -h"
  end
end
