# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RabbitmqMessageMonitor < Formula
  desc "Kubernetes Pod Helper Util"
  homepage "https://github.com/dhenkel92/rabbitmq-message-monitor"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhenkel92/rabbitmq-message-monitor/releases/download/v0.0.1/rabbitmq-message-monitor-0.0.1_Darwin_arm64.tar.gz"
      sha256 "328cc4d6b729f1baf82a77592006710c54142c9f92b8483673718507d2a6321a"

      def install
        bin.install "rabbitmq-message-monitor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/rabbitmq-message-monitor/releases/download/v0.0.1/rabbitmq-message-monitor-0.0.1_Darwin_x86_64.tar.gz"
      sha256 "46f18dc90ce54756efedda3c942b0b28534985e1bedc8059decb7d59c12e59fb"

      def install
        bin.install "rabbitmq-message-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhenkel92/rabbitmq-message-monitor/releases/download/v0.0.1/rabbitmq-message-monitor-0.0.1_Linux_x86_64.tar.gz"
      sha256 "7744fce69afa8ecce50b58d7a9f86af7600fd8046c98dea6a249a2684c05cd50"

      def install
        bin.install "rabbitmq-message-monitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhenkel92/rabbitmq-message-monitor/releases/download/v0.0.1/rabbitmq-message-monitor-0.0.1_Linux_arm64.tar.gz"
      sha256 "1ec35bb42df6648e9a17124d5b4508d4c7a630e48a856a60575cee3defaf2d60"

      def install
        bin.install "rabbitmq-message-monitor"
      end
    end
  end

  test do
    system "#{bin}/rabbitmq-message-monitor -h"
  end
end
